# Generated by Django 5.1.4 on 2025-01-09 11:45

import ckeditor.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_narration', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ErrorLog',
                'verbose_name_plural': 'ErrorLogs',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', ckeditor.fields.RichTextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='File Name')),
                ('file', models.FileField(upload_to='core/files/%Y/%M/%d')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='core/files/thumbnails', verbose_name='File thumbnail')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('App', 'Application'), ('Document', 'Document'), ('Audio', 'Audio'), ('Video', 'Video')], default='App', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=355)),
                ('message', ckeditor.fields.RichTextField(verbose_name='News Letter Content')),
                ('images', models.ImageField(blank=True, null=True, upload_to='Images/news_letters')),
                ('receivers', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Letter',
                'verbose_name_plural': 'News Letters',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SEOMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abstract', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SMS_Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Broadcast',
                'verbose_name_plural': 'SMS Broadcasts',
            },
        ),
        migrations.CreateModel(
            name='SystemUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_email', models.EmailField(help_text='Management Email for the System', max_length=254)),
                ('root_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Management Phone Number for the system', max_length=128, region=None)),
                ('user_support_email', models.EmailField(help_text='User Support Email', max_length=254)),
                ('user_support_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='User Support Email', max_length=128, region=None)),
                ('transaction_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Transaction Phone', max_length=128, null=True, region=None)),
                ('sales_commission', models.PositiveIntegerField(default=7, help_text='Commissions charged for Items sold')),
                ('info', ckeditor.fields.RichTextField()),
                ('privacy_policy', ckeditor.fields.RichTextField()),
                ('terms_of_use', ckeditor.fields.RichTextField()),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Address')),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=355, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('send_emails_alert', models.BooleanField(default=True)),
                ('use_gmail_smtp', models.BooleanField(default=True)),
                ('use_zoho_mail_smtp', models.BooleanField(default=False)),
                ('send_sms_alert', models.BooleanField(default=True)),
                ('use_twilio_sms', models.BooleanField(default=False)),
                ('use_africas_taking_sms', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemUtility',
                'verbose_name_plural': 'SystemUtility',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('image_illustration', models.ImageField(upload_to='Updates/Illustrations')),
                ('due_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Subscription',
            },
        ),
        migrations.CreateModel(
            name='SMS_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Subscription',
                'verbose_name_plural': 'SMS Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SystemEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Email Name')),
                ('email', models.EmailField(max_length=254)),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_email', to='core.systemutility')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Phone Number Name')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_phone', to='core.systemutility')),
            ],
        ),
        migrations.CreateModel(
            name='User_Inquiry',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contact')),
                ('is_answered', models.BooleanField(default=False)),
                ('post_inquiry', models.BooleanField(default=False)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inquiry',
                'verbose_name_plural': 'User Inquiries',
            },
            bases=('core.contact',),
        ),
    ]
