# Generated by Django 5.1.4 on 2025-02-06 13:46

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemutility',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemutility',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemutility',
            name='root_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Management Phone Number for the system', max_length=128, region='KE'),
        ),
        migrations.AlterField(
            model_name='systemutility',
            name='terms_of_use',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemutility',
            name='transaction_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Transaction Phone', max_length=128, null=True, region='KE'),
        ),
        migrations.AlterField(
            model_name='systemutility',
            name='user_support_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='User Support Phone', max_length=128, region='KE'),
        ),
        migrations.AddIndex(
            model_name='systemutility',
            index=models.Index(fields=['created'], name='system_util_created_45edf4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemutility',
            index=models.Index(fields=['updated'], name='system_util_updated_c832f8_idx'),
        ),
        migrations.AlterModelTable(
            name='systemutility',
            table='system_utility',
        ),
    ]
