# Generated by Django 5.1.4 on 2025-02-14 07:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_systemutility_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in international format', max_length=128, region=None, verbose_name='Phone Number')),
                ('otp', models.CharField(max_length=6, verbose_name='One-Time Password')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if this OTP has been verified')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of verification attempts allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the OTP was created')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the OTP expires')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this OTP is still active')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'otp'], name='core_otp_phone_n_a11c97_idx'), models.Index(fields=['created_at'], name='core_otp_created_654a6a_idx'), models.Index(fields=['is_verified'], name='core_otp_is_veri_93c816_idx')],
            },
        ),
    ]
