# Generated by Django 5.1.4 on 2025-10-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogs',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorlogs',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorlogs',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlogs',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlogs',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
