# Generated by Django 5.1.4 on 2025-10-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_errorlogs_code_errorlogs_file_errorlogs_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
