# Generated by Django 5.1.4 on 2024-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_analyzer', '0002_auto_20160719_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
