# Generated by Django 5.1.4 on 2025-01-10 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('cd544c67-a19b-4eb2-afcd-3a3667403aee'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
