# Generated by Django 5.1.4 on 2025-02-06 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a9098c7c-1c4d-4fb1-b045-bd69828a86b5'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
