# Generated by Django 5.1.4 on 2025-02-06 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('8f478979-af6b-4029-b38a-5edd36de7b96'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
