# Generated by Django 5.1.4 on 2025-02-14 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('d4c35e3c-d910-4502-afd6-73f54b3acb4c'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
