# Generated by Django 5.1.4 on 2025-02-14 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('8a05da90-b224-446c-99b1-3bc1bd69945b'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
