# Generated by Django 5.1.4 on 2025-10-01 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customerprofile_user_remove_otp_user_and_more'),
        ('finance', '0007_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='customer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='tip',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tip_sender', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('0585cd1d-b3ca-4f57-8130-ae3dcf1e4a0a'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile'),
        ),
    ]
