# Generated by Django 5.1.4 on 2025-10-02 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_receipt_customer_remove_tip_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('e965e2d9-304f-4091-b6e3-82242c8dabce'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
