# Generated by Django 5.1.4 on 2025-10-03 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('5fc94b34-f95c-47de-98e5-e2da0046957c'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
