# Generated by Django 5.1.4 on 2025-10-09 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('3bfd14ca-827c-4934-80b5-88eb1c98f07f'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
