# Generated by Django 5.1.4 on 2025-10-10 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('9a4ba832-e18c-4e7f-bc31-769a5572813b'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
