# Generated by Django 5.1.4 on 2025-10-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customerprofile_user_remove_otp_user_and_more'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='customer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='rating',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='ride',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('truck', 'Truck'), ('van', 'Van'), ('mini-bus', 'Mini-Bus'), ('lorry', 'Lorry'), ('trailer', 'Trailer'), ('pickup', 'Pickup'), ('SUV', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('cabriolet', 'Cabriolet'), ('roadster', 'Roadster'), ('targa', 'Targa'), ('hardtop', 'Hardtop'), ('rikshaw', 'Rikshaw'), ('other', 'Other')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('100cc', '100cc to 150cc'), ('151cc', '151cc to 250cc'), ('251cc', '251cc to 500cc'), ('501cc', '501cc to 1000cc'), ('1001cc', '1001cc to 1500cc'), ('1501cc', '1501cc to 2000cc'), ('2001cc', '2001cc to 2500cc'), ('2501cc', '2501cc to 3000cc'), ('3001cc', '3001cc to 3500cc'), ('3501cc', '3501cc to 4000cc'), ('4001cc', '4001cc to 4500cc'), ('4501cc', '4501cc to 5000cc'), ('5001cc', '5001cc to 6000cc'), ('6001cc', '6001cc and above')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_capacity',
            field=models.CharField(blank=True, choices=[('1 seater', '1 seater'), ('2 seater', '2 seater'), ('3 seater', '3 seater'), ('4 seater', '4 seater'), ('5 seater', '5 seater'), ('6 seater', '6 seater'), ('7 seater', '7 seater'), ('8 seater', '8 seater'), ('9 seater', '9 seater'), ('10 seater', '10 seater'), ('12 seater', '12 seater'), ('15 seater', '15 seater'), ('18 seater', '18 seater'), ('20 seater', '20 seater'), ('22 seater', '22 seater'), ('24 seater', '24 seater'), ('26 seater', '26 seater'), ('28 seater', '28 seater'), ('30 seater', '30 seater'), ('32 seater', '32 seater'), ('34 seater', '34 seater'), ('36 seater', '36 seater'), ('38 seater', '38 seater'), ('40 seater', '40 seater'), ('42 seater', '42 seater'), ('44 seater', '44 seater'), ('46 seater', '46 seater'), ('48 seater', '48 seater'), ('50 seater', '50 seater'), ('52 seater', '52 seater'), ('54 seater', '54 seater'), ('56 seater', '56 seater'), ('58 seater', '58 seater'), ('60 seater', '60 seater')], max_length=225, null=True),
        ),
    ]
