# Generated by Django 5.1.4 on 2025-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_feedback_customer_remove_rating_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacturing_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
