# Generated by Django 5.1.4 on 2025-10-01 20:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_termsacceptance'),
        ('rides', '0003_vehicle_manufacturing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.driverprofile')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RideMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance in kilometers')),
                ('estimated_eta_minutes', models.IntegerField(help_text='Estimated arrival time in minutes')),
                ('matching_score', models.FloatField(help_text='Matching score based on distance, rating, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Ride Matching',
                'verbose_name_plural': 'Ride Matchings',
                'ordering': ['-matching_score', 'distance_km'],
                'unique_together': {('ride_request', 'driver')},
            },
        ),
    ]
