# Generated by Django 5.1.4 on 2025-10-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_driverlocation_ridematching'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Base price in UGX', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Price per kilometer in UGX', max_digits=10),
        ),
    ]
