# Generated by Django 5.1.4 on 2025-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_vehicletype_base_price_vehicletype_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ride cost in UGX', max_digits=10, null=True),
        ),
    ]
