# Generated by Django 5.1.4 on 2025-10-01 22:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_riderequest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='route',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
