# Generated by Django 5.1.4 on 2025-10-01 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_termsacceptance'),
        ('rides', '0007_fix_route_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridematching',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this match expires if not accepted'),
        ),
        migrations.AddField(
            model_name='ridematching',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When driver responded', null=True),
        ),
        migrations.AddField(
            model_name='ridematching',
            name='response_time_seconds',
            field=models.IntegerField(blank=True, help_text='How long driver took to respond', null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When driver confirmed the ride', null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this request expires if no driver accepts', null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='matching_started_at',
            field=models.DateTimeField(blank=True, help_text='When driver matching started', null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_eta',
            field=models.DateTimeField(blank=True, help_text='Estimated pickup time', null=True),
        ),
        migrations.AlterField(
            model_name='ridematching',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_rate', models.FloatField(default=100.0, help_text='Percentage of ride requests accepted')),
                ('response_time_avg', models.FloatField(default=0.0, help_text='Average response time in seconds')),
                ('cancellation_rate', models.FloatField(default=0.0, help_text='Percentage of rides cancelled by driver')),
                ('completion_rate', models.FloatField(default=100.0, help_text='Percentage of rides completed')),
                ('reliability_score', models.FloatField(default=100.0, help_text='Overall reliability score (0-100)')),
                ('availability_score', models.FloatField(default=100.0, help_text='Availability score based on online time')),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total ride requests received')),
                ('accepted_requests', models.PositiveIntegerField(default=0, help_text='Total requests accepted')),
                ('declined_requests', models.PositiveIntegerField(default=0, help_text='Total requests declined')),
                ('timeout_requests', models.PositiveIntegerField(default=0, help_text='Total requests that timed out')),
                ('cancelled_rides', models.PositiveIntegerField(default=0, help_text='Total rides cancelled by driver')),
                ('completed_rides', models.PositiveIntegerField(default=0, help_text='Total rides completed')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='accounts.driverprofile')),
            ],
            options={
                'verbose_name': 'Driver Score',
                'verbose_name_plural': 'Driver Scores',
            },
        ),
    ]
