# Generated by Django 5.1.4 on 2025-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_ridematching_expires_at_ridematching_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='current_driver_index',
            field=models.IntegerField(default=0, help_text='Index of current driver being contacted'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='potential_drivers',
            field=models.JSONField(blank=True, default=list, help_text='List of driver IDs to contact sequentially'),
        ),
    ]
