# Generated by Django 5.1.4 on 2025-10-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_driverprofile_driver_status_and_more'),
        ('rides', '0009_add_sequential_matching_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='on_active_ride',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('on_active_ride', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
            ],
        ),
    ]
