# Generated by Django 5.1.4 on 2025-10-10 00:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_driverlocation_on_active_ride_driverlocationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocationhistory',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driverlocationhistory',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driverlocationhistory',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ridematching',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
