# Generated by Django 5.1.4 on 2025-10-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_remove_driverlocationhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_requests', to='rides.route'),
        ),
    ]
