[program:celery_worker]
command=/var/www/Zyra/venv/bin/celery -A RideNow worker --loglevel=info --concurrency=4
directory=/var/www/Zyra
user=admin
numprocs=1
stdout_logfile=/var/www-logs/zyra/worker.log
stderr_logfile=/var/www-logs/zyra/worker.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=998

[program:celery_beat]
command=/var/www/Zyra/venv/bin/celery -A RideNow beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/var/www/Zyra
user=admin
numprocs=1
stdout_logfile=/var/www-logs/zyra/beat.log
stderr_logfile=/var/www-logs/zyra/beat.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=999

# [program:celery_flower]
# command=/var/www/Zyra/venv/bin/celery -A RideNow flower --port=5555
# directory=/var/www/Zyra
# user=admin
# numprocs=1
# stdout_logfile=/var/www-logs/zyra/flower.log
# stderr_logfile=/var/www-logs/zyra/flower.log
# autostart=true
# autorestart=true
# startsecs=10
# stopwaitsecs=600
# killasgroup=true
# priority=997
# Note: Flower is not installed. To enable, install with: pip install flower
