[program:ridenow]
command=/home/avalon/Desktop/DEV/RideNow/venv/bin/gunicorn --bind 0.0.0.0:1101 --workers 4 --worker-class uvicorn.workers.UvicornWorker --access-logfile /var/log/django/ridenow_access.log --error-logfile /var/log/django/ridenow_errors.log --log-level info RideNow.asgi:application
directory=/home/avalon/Desktop/DEV/RideNow
user=avalon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/django/ridenow_supervisor.log
environment=DEBUG=False,ALLOWED_HOSTS="localhost,127.0.0.1,testserver,zyra.daraza.net"
