# Generated by Django 5.1.4 on 2025-01-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Designate the user as a client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Designate the user as a diver'),
        ),
    ]
