# Generated by Django 5.1.4 on 2025-10-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customerprofile_user_remove_otp_user_and_more'),
        ('finance', '0008_remove_receipt_customer_remove_tip_customer_and_more'),
        ('rides', '0002_remove_feedback_customer_remove_rating_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
