# Generated by Django 5.1.4 on 2025-10-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_driverprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('security_settings_update', 'Security Settings Update'), ('preferences_update', 'Preferences Update'), ('account_deletion', 'Account Deletion'), ('failed_login', 'Failed Login'), ('suspicious_activity', 'Suspicious Activity')], max_length=30)),
                ('description', models.TextField(help_text='Activity description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic location', max_length=100)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=True, help_text='Receive SMS notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('marketing_emails', models.BooleanField(default=False, help_text='Receive marketing emails')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', help_text='Who can see your profile', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('lg', 'Luganda'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Preferred language', max_length=5)),
                ('timezone', models.CharField(choices=[('Africa/Kampala', 'Africa/Kampala (EAT)'), ('Africa/Nairobi', 'Africa/Nairobi (EAT)'), ('Africa/Dar_es_Salaam', 'Africa/Dar_es_Salaam (EAT)'), ('Africa/Addis_Ababa', 'Africa/Addis_Ababa (EAT)'), ('Africa/Kigali', 'Africa/Kigali (CAT)'), ('Africa/Bujumbura', 'Africa/Bujumbura (CAT)'), ('Africa/Lagos', 'Africa/Lagos (WAT)'), ('Africa/Cairo', 'Africa/Cairo (EET)'), ('Africa/Johannesburg', 'Africa/Johannesburg (SAST)'), ('Europe/London', 'Europe/London (GMT)'), ('America/New_York', 'America/New_York (EST)'), ('America/Los_Angeles', 'America/Los_Angeles (PST)')], default='Africa/Kampala', help_text='Preferred timezone', max_length=50)),
                ('preferred_payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('wallet', 'Wallet')], default='cash', help_text='Preferred payment method for rides', max_length=20)),
                ('auto_accept_rides', models.BooleanField(default=False, help_text='Automatically accept ride requests (drivers only)')),
                ('max_ride_distance', models.PositiveIntegerField(default=50, help_text='Maximum ride distance in kilometers (drivers only)')),
                ('preferred_ride_types', models.CharField(blank=True, help_text='Preferred ride types (comma-separated)', max_length=200)),
                ('preferred_driver_rating', models.DecimalField(decimal_places=1, default=4.0, help_text='Minimum driver rating preference (clients only)', max_digits=2)),
                ('preferred_vehicle_type', models.CharField(choices=[('any', 'Any'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('motorcycle', 'Motorcycle')], default='any', help_text='Preferred vehicle type (clients only)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Two-factor authentication enabled')),
                ('two_factor_secret', models.CharField(blank=True, help_text='2FA secret key', max_length=32)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='2FA backup codes')),
                ('login_alerts', models.BooleanField(default=True, help_text='Receive login alerts')),
                ('session_timeout', models.PositiveIntegerField(default=60, help_text='Session timeout in minutes')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=3, help_text='Maximum concurrent sessions')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, help_text='Last password change')),
                ('password_expires_at', models.DateTimeField(blank=True, help_text='Password expiration date', null=True)),
                ('require_password_change', models.BooleanField(default=False, help_text='Require password change on next login')),
                ('account_locked', models.BooleanField(default=False, help_text='Account locked due to security reasons')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account locked until', null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Failed login attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Last failed login attempt', null=True)),
                ('data_sharing_consent', models.BooleanField(default=False, help_text='Consent to share data with partners')),
                ('analytics_consent', models.BooleanField(default=True, help_text='Consent to analytics tracking')),
                ('location_tracking', models.BooleanField(default=True, help_text='Allow location tracking')),
                ('api_access_enabled', models.BooleanField(default=False, help_text='Enable API access')),
                ('api_key', models.CharField(blank=True, help_text='API access key', max_length=64)),
                ('api_key_created_at', models.DateTimeField(blank=True, help_text='API key creation date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Settings',
                'verbose_name_plural': 'User Security Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Session expiration time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
