# Generated by Django 5.1.4 on 2025-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useractivitylog_userpreferences_usersecuritysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away'), ('offline', 'Offline')], default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
