"""
Django settings for RideNow project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import environ
from pathlib import Path
from datetime import timedelta

SITE_ID = 1

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environ
env = environ.Env(DEBUG=(bool,False))
environ.Env.read_env(env_file=".env")

# Set the GDAL_LIBRARY_PATH environment variable

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "zyra.daraza.net", "www.zyra.daraza.net"]

SITE_ID = 1

CSRF_TRUSTED_ORIGINS = ['https://zyra.daraza.net', 'https://www.zyra.daraza.net', 'http://localhost:8000', 'http://127.0.0.1:8000']

# Nginx proxy configuration
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production security settings
# These settings are generally safe to run in production and should not block service,
# provided your environment is properly configured (e.g., Redis is running, log directories exist, HTTPS is enabled).
# However, misconfiguration (e.g., missing Redis, missing log directory, or not running behind HTTPS) can cause issues.
# Review each setting and ensure your infrastructure matches.

if not DEBUG:
    # Security headers
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS. Requires HTTPS to be enabled.
    SECURE_HSTS_SECONDS = 31536000  # 1 year. Only set if HTTPS is always used.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Session security
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False # Blocks Javascript access
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Additional security
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    
    # Logging configuration
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': '/var/www-logs/zyra/zyra.log',
                'formatter': 'verbose',
            },
            'error_file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': '/var/www-logs/zyra/zyra_errors.log',
                'formatter': 'verbose',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'error_file'],
                'level': 'INFO',
                'propagate': True,
            },
            'rides': {
                'handlers': ['file', 'error_file'],
                'level': 'INFO',
                'propagate': True,
            },
            'accounts': {
                'handlers': ['file', 'error_file'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }
    
    # Cache configuration for production
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
        }
    }
    
    # Database connection pooling (moved to after DATABASES definition)
    pass
    
    # Static files optimization
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
    
    # Email backend for production
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    
    # File upload settings
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
    
    # Session settings
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
    SESSION_COOKIE_AGE = 86400  # 24 hours

# Application definition

INSTALLED_APPS = [
    'daphne',
    
    'django.contrib.gis',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    #Local
    'accounts',
    'core',
    'finance',
    'tracking_analyzer',
    'rides',

    #Third party
    # 'taggit',
    'allauth',
    # 'captcha',
    'ckeditor',
    # 'crispy_forms',
    # 'simple_history',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth.account',
    'drf_spectacular',
    'phonenumber_field',
    # 'crispy_bootstrap5',
    'django_user_agents',
    'django_celery_beat',
    'channels',
    'import_export',
    'django_filters',
    'django_countries',
    'allauth.socialaccount',
    # 'rest_framework_api_key',
    # The social providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.apple',

    # 'django_otp',
    # 'two_factor',
    # 'two_factor.plugins.email',  # <- if you want email capability.
    # 'django_otp.plugins.otp_totp',
    # 'django_otp.plugins.otp_email',  # <- if you want email capability.
    #'two_factor.plugins.phonenumber',  # <- if you want phone number capability.
    # 'django_otp.plugins.otp_static',
    # # 'two_factor.plugins.yubikey',  # <- for yubikey capability.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    
    # Third Party
    'allauth.account.middleware.AccountMiddleware'
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.authentications.CustomAuthenticationBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'RideNow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RideNow.wsgi.application'
ASGI_APPLICATION = 'RideNow.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': env('POSTGRES_DBNAME'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASS'),
        'HOST': env('PG_HOST'),
        'PORT': env('PG_PORT'),
    }
}

# Production database optimizations
if not DEBUG:
    DATABASES['default']['CONN_MAX_AGE'] = 600


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static',]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#GDAL
GDAL_LIBRARY_PATH = fr'{env("GDAL_LIBRARY_PATH")}'
GEOS_LIBRARY_PATH = fr'{env("GEOS_LIBRARY_PATH")}'

GEOIP_PATH =  (os.path.join(BASE_DIR, 'GEOIP_Database'))


# TWILIO
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER')

# Africa's Talking
AFRICAS_TALKING_APIKEY = env('AFRICAS_TALKING_APIKEY')
AFRICAS_TALKING_USERNAME = env('AFRICAS_TALKING_USERNAME')
AFRICAS_TALKING_SENDER_ID = env('AFRICAS_TALKING_SENDER_ID')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'   
# SMTP
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply@daraza.net'
EMAIL_HOST_PASSWORD = env('ZOHOMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'noreply@daraza.net'

# Google Maps
GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY', default='')

# Mapbox
MAPBOX_ACCESS_TOKEN = env('MAPBOX_ACCESS_TOKEN', default='pk.eyJ1IjoiYWpyYWxsYW4iLCJhIjoiY21hd3N5bWJjMGY4YzJqc2V6aG55MHU4byJ9.LHLL7YKtl_V-1xkGVyFhcw')

# ==================== DJANGO ALLAUTH CONFIGURATION ====================

# Django Allauth Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Optional for social logins, mandatory for email signups
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGIN_REDIRECT_URL = '/rides/book/'  # Default to ride booking for clients
ACCOUNT_SIGNUP_REDIRECT_URL = '/rides/book/'  # Default to ride booking for clients
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'

# Rate limiting (replaces deprecated ACCOUNT_LOGIN_ATTEMPTS_LIMIT/TIMEOUT)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
    'signup': '10/d',  # 10 signups per day per IP
}

# Social Account Settings
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Social providers already verify emails
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account from social login
SOCIALACCOUNT_LOGIN_ON_GET = False  # Require POST for security
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from provider
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'
SOCIALACCOUNT_STORE_TOKENS = True  # Store OAuth tokens for future API calls

# Provider specific settings
# NOTE: APP credentials are stored in database (SocialApp model)
# Only configure provider-specific behavior here, not credentials
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        # APP credentials configured in Django Admin → Social applications
    },
    'apple': {
        'SCOPE': ['name', 'email'],
        'AUTH_PARAMS': {
            'response_mode': 'form_post',
        },
        # APP credentials configured in Django Admin → Social applications
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Required for drf-spectacular
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# API Documentation with Custom Branding
SPECTACULAR_SETTINGS = {
    'TITLE': 'Zyra API Documentation',
    'DESCRIPTION': '''
    ## 🚗 Welcome to Zyra API
    
    Comprehensive API for the Zyra ride-sharing platform. This API enables seamless integration 
    for mobile apps, web applications, and third-party services.
    
    ### Features:
    - 🔐 **Authentication** - JWT tokens, Social OAuth, Phone/Email login
    - 🚕 **Ride Management** - Book, track, and manage rides
    - 👥 **User Profiles** - Client and driver account management
    - 💰 **Payments** - Wallet, transactions, and refunds
    - 📊 **Analytics** - Real-time tracking and reporting
    
    ### Getting Started:
    1. Register for an account or login
    2. Obtain JWT access token
    3. Include token in Authorization header: `Bearer <token>`
    4. Start making API calls!
    
    ### Support:
    - 📧 Email: support@zyracab.com
    - 📱 Phone: +256789079301
    - 📚 Full Documentation: [docs.zyra.app](https://docs.zyracab.com)
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    
    # Custom branding
    'FAVICON': '/static/img/favicons/favicon-32x32.png',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
        'syntaxHighlight.theme': 'monokai',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 3,
        'docExpansion': 'list',
        'displayRequestDuration': True,
        # Custom UI colors to replace purple with green
        'theme': {
            'primary': '#21c45d',
            'secondary': '#1db954',
        },
    },
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5',
    'SWAGGER_UI_FAVICON_HREF': '/static/img/favicons/favicon-32x32.png',
    
    # Security schemas
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT Authentication - Obtain token from /api/accounts/auth/login/'
            },
            'cookieAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Session cookie authentication'
            }
        }
    },
    'SECURITY': [
        {'Bearer': []},
        {'cookieAuth': []},
    ],
    
    # Tags for better organization
    'TAGS': [
        {'name': 'Authentication', 'description': 'User registration, login, and token management'},
        {'name': 'Social Authentication', 'description': 'Google and Apple OAuth integration'},
        {'name': 'User Profile', 'description': 'User account and profile management'},
        {'name': 'Rides', 'description': 'Ride booking, tracking, and management'},
        {'name': 'Drivers', 'description': 'Driver registration and dashboard'},
        {'name': 'Payments', 'description': 'Wallet, transactions, and payment processing'},
        {'name': 'Security Settings', 'description': 'User security and privacy settings'},
    ],
    
    # Preprocessing
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    
    # Schema customization
    'ENUM_NAME_OVERRIDES': {},
    'SCHEMA_COERCE_PATH_PK_SUFFIX': True,
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

# Django Channels Configuration
if DEBUG:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }
else:
    # Production Redis configuration for WebSockets
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [('127.0.0.1', 6379)],
                "capacity": 1500,
                "expiry": 10,
            },
        },
    }

# Celery configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Kampala'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Production-specific settings
if not DEBUG:
    
    # Admin configuration
    ADMIN_URL = 'admin-secure-url-change-this/'
    
    # Performance optimizations
    CONN_MAX_AGE = 600
    
    # Error reporting
    ADMINS = [
        ('Admin', 'admin@zyra.daraza.net'),
    ]
    
    # Email configuration for production
    SERVER_EMAIL = 'noreply@zyra.daraza.net'
    
    # Celery configuration for production

    
    # Rate limiting
    RATELIMIT_ENABLE = True
    RATELIMIT_USE_CACHE = 'default'
    
    # Monitoring and health checks
    HEALTH_CHECK = {
        'DISK_USAGE_MAX': 90,  # percent
        'MEMORY_MIN': 100,     # in MB
    }
